### ISSUE TITLE
編集中、カーソルが思わぬ場所に移動してしまう

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#102]
画面が書き換わるると、カーソルが文書末に移動して、ユーザは作業中のカーソルを見失ってしまう。

https://user-images.githubusercontent.com/31482860/135438427-ab87a1ef-6ae4-4294-867b-6cffc4ca1417.mov

**Comment by MurakamiShinyu** [comment]
たぶん現在は解決済みなのでクローズします。まだこの現象があったら再オープンしてください。
