### ISSUE TITLE
利用できるスタイル（Theme）を最新のものに変更する

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#103]
現在利用できるスタイル（Theme）はアルファ版当時のものです。

 全てでなくともよいので、[vivliostyle-themes](https://www.npmjs.com/search?q=keywords%3Avivliostyle-theme)で公開中のThemeが使えるようにしたいところです。

**Comment by MurakamiShinyu** [comment]
対応済みなのでクローズします。
