### ISSUE TITLE
特定のアカウントでログイン後エディタ画面に移行しない

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#111]
- 数ヵ月前からずっと続いている症状
- プライマリーアカウントでこの症状が出るが、テスト用に作成したアカウントでは問題なく動作
- ログイン後、表示されるはずのプランチが表示されない
- Chrome開発ツールでみると、405エラーが発生
- やってみたこと
    - GitHub Appsの再インストールと、GitHub Access Tokenの更新
    - 開発ツールでキャッシュ無効化

スクリーンショット動画を撮影してみました

https://user-images.githubusercontent.com/31482860/136312096-983af24e-0e6a-4214-af08-db00b6ba028d.mov

**Comment by AyumuTakai** [comment]
動画の1:06あたりからの内容で、本来CacheStorageにキャッシュされるべきではないファイルがキャッシュされているように見受けられます。(リポジトリ選択の段階で/viewer/*がキャッシュされるはずがない)

これは別アカウントでログインしたときにキャッシュされた内容ではないかと思います。
ここに認証に関するURLが含まれていると問題が発生する可能性があるかもしれません。

一度ログアウトしたあとサイトデータを全て削除したあと、再度ログインを試して頂けないでしょうか。

![remove_sitedata](https://user-images.githubusercontent.com/2599195/136320451-b68f3756-2e3a-4b91-a725-796f12f22d03.png)

**Comment by ogwata** [comment]
お返事感謝です。
ご指示のように操作してみましたが、残念ながら変わりません。
どうがをさつえい

**Comment by AyumuTakai** [comment]
検証ありがとうございます。
405エラーなので、キャッシュストレージに対してPOSTやPUTをしたのかと思いましたが違ったようです。

Pubのソースコードを見たところ、web/src/pages/api/github/repos.ts の 26行目に関係していそうな処理があるので調べてみます。

**Comment by ogwata** [comment]
以下のPRのマージ後、改めて動作を確認してみました

- [Bump ansi-regex from 5.0.0 to 5.0.1 in /web #104](https://github.com/vivliostyle/vivliostyle-pub/pull/104)
- [feat: change file select cursor #99 #105](https://github.com/vivliostyle/vivliostyle-pub/pull/105)
- [fix: logout error #107](https://github.com/vivliostyle/vivliostyle-pub/pull/107)
- [fix: cached files give 404 Not found error #110](https://github.com/vivliostyle/vivliostyle-pub/pull/110)
- [fix fileupload does not working #112](https://github.com/vivliostyle/vivliostyle-pub/pull/112)


しかし、症状は変わらず、やはりリポジトリは表示されず、エディタ画面に移行せず、開発ツールをみると405エラーが出ています。動画を撮影してみました。

https://user-images.githubusercontent.com/31482860/136664262-59a1b498-4f9e-4d05-9970-32d3c04ddef6.mov

**Comment by AyumuTakai** [comment]
リポジトリリストが表示されるか否かとリポジトリが選択できた後の話では内部的に別の問題のように見えます。

リポジトリリストが表示されるためには、firebaseのアカウントにgithubAccessTokenという項目が必要で、
これが無いとリスト表示時点で405エラーになります。

テストユーザの方はリポジトリがひとつは表示されているので上記の問題はクリアしているようです。

今気付きましたが、テストユーザの方のリポジトリにvivliostyle.config.jsが無いのでは。
ウィンドウ左側のファイルリストはvivliostyle.config.jsのentryを元に表示するので、vivliostyle.config.jsが無いと何も表示されません。
これはリポジトリ内のファイルを全て表示するように修正したいところです。

**Comment by MurakamiShinyu** [comment]
これはすでに解決済みかと思うのでクローズします。違っていたら再オープンしてください。

**Comment by ogwata** [comment]
この問題、現在も解決できていません。動画を撮影してみました。

https://user-images.githubusercontent.com/31482860/174711764-2747d9d7-42fa-4edc-9648-7fca6c64f4a2.mov

dev toolsのスクリーンショットは下記の通りです。
![スクリーンショット 2022-06-21 12 42 09](https://user-images.githubusercontent.com/31482860/174711820-64b96eda-90c2-410c-a3af-055cbee423ea.png)

もしかしたら、GitHubアカウントの設定に依存する問題なのかもしれません。
必要な情報があれば言ってください。

**Comment by ogwata** [comment]
補足情報です。
Windows 10Pro (21H2)+Chrome 102.0.5005.63 (64bit)でVivliostyle Pubにログインしたところ、Mac OSと同様、リポジトリが表示されません。デバイスに依存する問題ではないようです。

**Comment by ogwata** [comment]
@MurakamiShinyu さんのおかげで、本件無事に解消しましたので、記録に残しておきます。

Firebaseの管理画面でAuthentication > Users をみたところ、私のアカウントについて、以下のように表示されました。

![Screen Shot 2022-10-09 at 11 02 31](https://user-images.githubusercontent.com/31482860/194759818-12611675-c462-414a-a7b3-038f36fcdf0f.png)
![Screen Shot 2022-10-09 at 11 06 09](https://user-images.githubusercontent.com/31482860/194759819-36b4d854-b3da-4811-a974-c4e11324ff4e.png)

上記の2つのメールアドレスは、どちらも問題になっているアカウントに紐付いています。そして、長い時間アカウント設定はいじっていません。それなのにvivliostyle.orgのアドレスは今から数日前に作成されたことになっており、矛盾があります。

そこで両方のメールアドレスを両方ともアカウントを削除した上で、Git
