### ISSUE TITLE
アカウントに接続したリポジトリのうち、一部しか表示されなくなった

### ISSUE THREAD

**Issue by ogwata-test** [vivliostyle/vivliostyle-pub#113]
以下の動画で表示されているリポジトリは招待されたもので、自分の作成したリポジトリが表示されません。
Chromeの開発ツールをみるとエラーは出ていません。

https://user-images.githubusercontent.com/31482860/136665842-8328a7c1-a8cf-4480-8168-1ca3380eb300.mov

Safariを使って、同じGitHubアカウントでVivliostyle Pubにログインすると、Chromeと同じで一部のリポジトリしか表示されません。開発ツールをみると、`SyntaxError: Invalid regular expression: invalid group specifier name`が出ています。

https://user-images.githubusercontent.com/31482860/136666011-88084779-295c-4e5d-80fc-91a931afcd85.mov

最後に、Firefoxでも試してみました。同様に一部のリポジトリだけ表示されます。こちらは404エラーが出ています。

https://user-images.githubusercontent.com/71211063/136666276-8f714287-c0b9-450e-9567-2f169c57246d.mov

**Comment by ogwata** [comment]
ogwata-testは私です（ややこしいことをして、すみません）。

**補足その1**
まず、表示されているリポジトリは正常に表示されます。

**補足その2**
この症状は、今発症した訳ではありません。記憶をたどると、10月7日（木曜）夕方に初めてこの症状を確認しました。ところが、別のアカウントでログインしたタイミングで、全く別のトラブルが発生しました。具体的には、404エラーでプレビューが表示されなくなってしまいました。これを報告したのが、Slackの以下の投稿です。

https://vivliostyle.slack.com/archives/G012JJWU23U/p1633594010050500

上記について、@AyumuTakai さんが、その時出していたPRがマージされたら解決するはずと回答してくれ、そのマージ後に改めて試したところ、本Issueのエラーが再度発症したというわけです。

なお、補足その1で書いたように、いったんブランチを選択してしまえば正常に表示されるので、上記404エラーの問題は解決したように思えます。

**Comment by ogwata** [comment]
今改めて確認したところ、症状が解消していることが確認できたのでクローズします。

![スクリーンショット 2022-06-21 12 18 17](https://user-images.githubusercontent.com/31482860/174709129-a65e559a-7ec9-4e49-85eb-cb310f86014a.png)
