### ISSUE TITLE
デフォルトのスタイルシートの指定を無しにする

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#119]
## 問題の所在

現在、Vivliostyle Pubが使っている[デフォルトのスタイルシート](https://raw.githubusercontent.com/youchan/viola-project/master/main.css)には、以下のような問題が指摘されています。

1. H1の行頭で、カウンタ「0.」が表示される
 2. コードブロックで全体を包括する矩形が確保されず、以下のような問題が生じる
    - 1行目がわずかにインデントされる
    - 行間に空白が生じ、行端でブロックが終わってしまう

1は複数のコンテンツからなるグループ誌を念頭においた機能ですが、適切なスタイルシートでの指定が必要です。それをしないと「0.」が表示されてしまうことから問題が発生します。

2についてはコードブロックは通常pre要素で領域全体について指定をするところ、そのpre要素に対してはスタイルが定義されておらず、内包するcode要素で背景色、角丸などが定義されていることが原因です。code要素はインライン要素なので、インラインにだけスタイルが適用されてしまうのです。

いずれも、現在のデフォルトのスタイルシートが、Vivliostyle Pubの原型であるオンラインエディタ[Viola](https://vivliostyle.org/ja/blog/2018/11/22/introduction-of-viola/)に由来することが原因です。当たり前ですが、Violaが作られたのはVFMよりも前なので、Vivliostyle PubがVFMによって生成するHTMLに合っていないのです。

## あるべき対策

Vivliostyle Pubのデフォルトとしてはスタイルシートの指定が無い状態とし、Vivliostyle Viewerのデフォルトをそのままを使うのがよさそうです。

ただし、スタイルシート指定なし（デフォルトスタイルのみ）の場合、ページサイズの指定もデフォルトの`auto`になるので、表示エリアの大きさがページサイズになります。これでは本を作るのには向かないでしょうから、ページサイズの指定はできたほうがよいでしょう。これについては、Vivliostyle Viewerのページサイズの指定を使うとよいと思います。

~~結論として、現在のデフォルトのスタイルシートを、ページサイズの指定だけのものに差し替えるという対応がよいでしょう。~~

なお、本Issueの解決策は当面のものであり、近い将来デフォルトのスタイルシートの求められる機能を検討する必要があります。その結果、前述のようなVivliostyle Viewerのページサイズの指定も不要になるでしょう。

関連して、デフォルトのスタイルシートは、現在は以下のように個人のテーマとしてホスティングされています。

```
{
    name: 'Viola',
    css:
      'https://raw.githubusercontent.com/youchan/viola-project/master/main.css',
  },
```

デフォルトのスタイルシートはVivliostyle関連のリポジトリからホスティングしたほうが良いでしょう。

なお、Vivliostyle Viewerの設定で指定されたスタイルシートは、URLパラメータの`&userStyle=…`に反映されます。これを`iframe.contentWindow.location.hash`で見ることができるので、PDF出力のときのページサイズで同じページサイズ設定を使うのにも利用できると思います。

## 参考

- [Slack: #vivliostyle-pub](https://vivliostyle.slack.com/archives/CR14JBXCJ/p1634659438001800)
- [hs9587/date_calender](https://github.com/hs9587/date_calender/tree/20191027-0)

**Comment by MurakamiShinyu** [comment]
Pubのデフォルトのスタイルシートは、当面は「無し」として、ページサイズの指定はVivliostyle Viewerの設定メニューからできればよいのでないかというのが私の案です。

Vivliostyle CLI では、コマンドラインあるいはconfigから指定されたページサイズをVivliostyle ViewerのURLパラメータに渡しています。ソースコードの次の部分:
https://github.com/vivliostyle/vivliostyle-cli/blob/main/src/server.ts#L58-L63
これにより、preview コマンドのコマンドラインで指定したものが、Viewerの設定メニューに反映されます。

ユーザーがViewerの設定メニューでページサイズを変更すると、それがURLのパラメータに反映されます。Pubのプレビューは、`<iframe>` でVivliostyle Viewerを表示しているので、Pubのプログラムのほうでは `iframe.contentWindow.location.hash` を調べると、ユーザーが設定メニューから設定したスタイルを得ることができるので、PDF生成のときにそれを使うようにすれば、Viewerの設定メニューでの設定をPDF出力にも反映させることが可能になるはずです、。

**Comment by ogwata** [comment]
なるほど、デフォルトのスタイルシートを差し替えるのではなく、無しにして問題があればVivliostyle Viewerの設定メニューから調整するということですね。

了解しました。
Issueのタイトルを「デフォルトのスタイルシートの指定をなしにする」に変えるのはどうでしょう？
