### ISSUE TITLE
エディタとプレビューのペインの幅を任意のサイズに変更可能にする

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#120]
現在のUIでは、エディタとプレビューの幅をユーザの好みのサイズに変更できません。
エディタとプレビューの仕切りを変更可能にすることで、任意のサイズに変えられるようにできるのではないでしょうか。

**Comment by MurakamiShinyu** [comment]
対応済みなのでクローズします。
