### ISSUE TITLE
Hard new lineが使えない

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#121]
エディタで`<br>`を入力しても、プレビュー画面に反映されないようです
![スクリーンショット 2021-11-12 17 07 29](https://user-images.githubusercontent.com/31482860/141435074-b645c002-0e90-4335-a890-0a55dd943c0b.png)
。

**Comment by MurakamiShinyu** [comment]
HTML出力を見ると
https://github.com/ogwata-book/mybook/blob/main/chapter-3/section-2.html
`<br>` は出力されているし、
Vivliostyle ViewerでこのHTMLを表示しても改行はされています。

https://vivliostyle.vercel.app/#src=https://github.com/ogwata-book/mybook/blob/main/chapter-3/section-2.html&style=https://github.com/ogwata-book/mybook/blob/main/css/style.css

私の方で、Vivliostyle Pubを試すと、`<br>` タグ、または行末のスペース２つで問題なく改行できました。
<img width="1903" alt="Screen Shot 2021-11-12 at 18 42 51" src="https://user-images.githubusercontent.com/3324737/141446121-e4cd76c5-5f5f-4488-9d22-eb600f2d8eaf.png">

**Comment by ogwata** [comment]
エディターでテキストを追加して “Save document” をクリックしても、プレビューに変化がありません。どうも文書（リポジトリ）の更新が、Vivliostyle Pubに変更されていないようです。
動画を撮影してみました。

https://user-images.githubusercontent.com/31482860/141460818-832a72e4-1209-45e4-9c29-ba618df10b56.mov

なお、リポジトリ上のmybook/chapter-3/section-2.mdは、確かに変更されています。


![スクリーンショット 2021-11-12 20 34 47](https://user-images.githubusercontent.com/31482860/141460986-23870db1-f282-43c8-acd1-a06dba8320c7.png)

**Comment by ogwata** [comment]
おそらく #122 も同じ原因と思われます。

**Comment by ogwata** [comment]
同じogwata-bookアカウントで、新規リポジトリを作成して試してみましたが、やはり404エラーでプレビューが表示されません。

![スクリーンショット 2021-11-12 22 13 14](https://user-images.githubusercontent.com/31482860/141472861-4b8fe04d-aeef-44d5-8382-5e8da5239f6d.png)

次は新規アカウントで試してみます……。

**Comment by ogwata** [comment]
新しいアカウントを作って試しましたが、やはり404エラーがでました。＿|￣|○

![スクリーンショット 2021-11-12 22 42 37](https://user-images.githubusercontent.com/31482860/141476571-c335b06b-56eb-48fe-9eeb-7ec41a3af85c.png)

**Comment by AyumuTakai** [comment]
検証の結果、vivliostyle.config.jsにthemeの指定があると中間処理に失敗してhtmlファイルが作成されないことを確認しました。
テーマ周りは全面的に再構築したいので、合わせて修正できるように進めます。

**Comment by ogwata** [comment]
ちょっと整理しますと、本Issue、ならびに #122は、11月8日には外部スタイルシートを読み込ませていても問題は発生しませんでした。

https://twitter.com/ogwata/status/1457715374221246464?s=20

ところが、4日後の11月12日午後、突然404エラーが発生しました。

また、上記@MurakamiShinyuさんの[コメント](https://github.com/vivliostyle/vivliostyle-pub/issues/121#issuecomment-966963041)を読むと、同じvercel.appにアクセスしていたのに、私のブラウザだけで起こったわけです。なんとも興味深いことです。
