### ISSUE TITLE
MathML 数式不調、一部タグがそのまま出てくる

### ISSUE THREAD

**Issue by hs9587** [vivliostyle/vivliostyle-pub#131]
MathMK の数式が一部うまく出てこないです。
タグがそのまま出てきてしまいます。

ブラウザでこのような数式になる MsthMLデータ
![mml err](https://user-images.githubusercontent.com/1061077/145948037-10920a01-22b4-4167-88b9-408fc70cb252.png)

[mml.err.md](https://github.com/vivliostyle/vivliostyle-pub/files/7709375/mml.err.md)
が、Vivliostyle Pub 画面にて
![mml err vivpub](https://user-images.githubusercontent.com/1061077/145949436-75c139f8-489c-4881-8c48-4c668832b893.png)
のように、左辺項「h」のみ良いように出てきて、それ以降はタグがそのままになります。

**Comment by MurakamiShinyu** [comment]
Markdownの中にHTMLコード（MathMLコードでも）を入れる場合、途中に空白行を入れることはできません。

Markdownの中にHTMLを入れる HTML Blockの仕様: https://github.github.com/gfm/#html-blocks

Markdownのこの仕様は分かりにくいかもしれませんが、HTMLコードの途中に空白行があると、そこでHTMLブロックが終了することになっているということです。

つまり、

```
<math>
  <mrow>
    <mi>h</mi>
```

これで HTMLブロックが終了します。だから「h」だけがHTMLの中のMathMLとして処理されることになります。

そしてそのあとに次の部分はコードブロックとして解釈されます。
```
    <mo>=</mo>

    <mfenced …>
      <mover>…</mover>
    </mfenced>
```

これは Indented code block https://github.github.com/gfm/#indented-code-blocks の仕様によりものです。
（4つ以上のスペースでインデントされたブロックはコードブロックとして出力される）

MathMLコードの中の空白行を削除して試してみてください。

**Comment by MurakamiShinyu** [comment]
@hs9587 

上記のとおり、これは正常な動作ですので、このissueはクローズします。
また気がついたことがあればissue登録お願いします。

**Comment by hs9587** [comment]
コメントありがとうございます。
Markdown中の HTMLの仕様だったんですね、クローズ了解しました。

> MathMLコードの中の空白行を削除して試してみてください。
こちら、空白文字「 」一文字だけの行にするというのは行儀悪いですかね。

MathML ソース書いてて左辺と右辺が目立つように書きたいのです

**Comment by MurakamiShinyu** [comment]
> こちら、空白文字「 」一文字だけの行にするというのは行儀悪いですかね。

Markdown仕様（VFMが準拠しているCommonMarkやGFM）での空白行の定義 https://github.github.com/gfm/#blank-line は次のようになってます:

> A line containing no characters, or a line containing only spaces (U+0020) or tabs (U+0009), is called a blank line.

つまり、空白文字「 」一文字だけの行も空白行であり、ブロックの区切りになることに変わりません。
（ただしvfm（Vivliostyle Pubで使われるMarkdown→HTML変換ツール）での動作を確認したところ、空白文字があると空白行扱いにならないことがあるようです。これはバグですので、vfmを修正することになります）

したがって、その方法は使えません。

HTMLのコメント `<!-- -->` を使って次のように書くことならできるはずです。

```html
<math>
  <mrow>
    <mi>h</mi>
<!---->
    <mo>=</mo>
<!---->
    <mfenced open="|" close="|">
      <mover><mi>HP</mi><mo>&rarr;</mo></mover>
    </mfenced>
  </mrow>
</math>
```

あるいは、Markdownを使わないで、HTMLを使うならばこの問題はありません。

**Comment by hs9587** [comment]
空白行の定義、了解しました。
(vfm のバグ見つかって良かったです)

**Comment by MurakamiShinyu** [comment]
vfmのissue登録しました:

- https://github.com/vivliostyle/vfm/issues/135
