### ISSUE TITLE
mainブランチ以外のブランチのファイルを削除しようとするとmainブランチのファイルが削除される

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#133]
mainブランチとtestブランチがあるリポジトリで、Vivliostyle Pub (vivliostyle-pub-develop-proto.vercel.app) でtestブランチを開いて、リポジトリのファイル一覧からファイルを選んで右クリック→Delete Fileで削除しようとしたとき、testブランチのそのファイルは削除されないで、mainブランチにあるファイルが削除されます。

確認お願いします。

**Comment by AyumuTakai** [comment]
ファイル管理とディレクトリ管理は機能を全面的に書き換えているところなので少々お待ち下さい。

**Comment by MurakamiShinyu** [comment]
解決済みなのでクローズします。
