### ISSUE TITLE
Rename Fileでエラー、元のファイルのコピーで新しいファイルが生成されるが元のファイルが削除されない

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#134]
（ユーザーからの報告から）

「Rename File」で、「Renameに失敗しました」というエラーが出る。
元のファイルのコピーで新しい名前のファイルが生成されはしている（GitHubのコミット "create file"）。
しかし、元のファイルは削除されていない（エラーなしにRenameできたときはGitHubのコミット "delete file" があるが、そのコミットがない）

再現条件はわかりませんが、いくつものファイルを編集したあとRenameするということを繰り返していて、最初はエラーなくRenameできていたのが、途中からエラーになるようになったらしいです。

**Comment by KazuyoshiTokue** [comment]
「Rename File」で、「Renameに失敗しました」というエラーが出る。
この不具合については、その後アップデートされていますか。先日のヴァージョンアップ以降の状況を教えてください。

**Comment by MurakamiShinyu** [comment]
@AyumuTakai これは修正済みのようなので、closeしてよいですね？
