### ISSUE TITLE
VFM チートシート表示機能を追加する

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/vivliostyle-pub#136]
ヘルプのひとつとして VFM の記法チートシートを表示する。

**Comment by akabekobeko** [comment]
Redmine の textarea 上部にあるツールバーからヘルプを表示すると、以下のポップアップ ウィンドウで Matkdown 記法が解説されます。

![ss-01](https://user-images.githubusercontent.com/1257526/148896156-39fd89c6-c0b7-49f2-9480-8dcd0f4e8308.png)

GitHub Issues では右下の「M↓」アイコンをクリックすることで [Basic writing and formatting syntax - GitHub Docs](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) が別ページで開かれます。

2022/1/8 の開発者会議ではポップアップ ウィンドウより別ページで開くほうがよさそうという話があったので GitHub Issue 形式かつ [Vivliostyle Flavored Markdown - VFM: Vivliostyle Flavored Markdown](https://vivliostyle.github.io/vfm/#/vfm) を対象とするのがよいかもしれません。チートシートを別立てするなら Redmine のように GFM 部分も含めて記法とプレビューを併記する感じですかね。

**Comment by ogwata** [comment]
とても良いと思います。
この形にする場合、原稿はどのように用意すればよいのでしょう？

**Comment by akabekobeko** [comment]
Pub 側としてどのように表示するのかによります。VFM 仕様の一つとするなら VFM リポジトリーの `docs/` へ置いて、Pub からはそこへリンクすることになるでしょう。

Pub のリソースとして持つ場合は、どのようにすればよいかわかりません。既に Pub としてヘルプなどを提供している場合は、その一部として配置することになるのだと思います。

**Comment by ogwata** [comment]
了解です。Pubのチームで話し合うことにしましょう。

**Comment by akabekobeko** [comment]
補足です。コメントで引用したスクリーンショットは Redmine の Markdown 構文ヘルプで、実体は HTML 形式です。

- [redmine/public/help/en at master · redmine/redmine](https://github.com/redmine/redmine/tree/master/public/help/en)
- [redmine/public/help/ja at master · redmine/redmine](https://github.com/redmine/redmine/tree/master/public/help/ja)

VFM のベース部分である CommonMark/GFM 部分の参考になると思います。なお Redmine のライセンスは GNU General Public License v2 ですので、参考とされるにしても流用や引用についてはこの点に気をつけてください。

**Comment by akabekobeko** [comment]
変換前後を横に並べることも考慮するなら Redmine のように HTML で書くのがよさそうです。少なくとも VFM のような Markdown 系だとコード ブロックの関係で HTML 埋め込みを利用しないとこのようには書けません。

**Comment by MurakamiShinyu** [comment]
メニューの  Help→VFM Spec で実装済みなので、このissueはクローズします。チートシートとしての使い勝手の向上など、さらに検討が必要になったら新しいissueにしてください。
