### ISSUE TITLE
保護されたブランチで編集してSave documentしたとき

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#141]
リポジトリのmainブランチにbranch protectionの設定により直接書き込みできないようにしても、Vivliostyle Pubでそのブランチで編集して「Save document」をクリックして「ファイルを保存しました」とメッセージが出ます。しかし、実際はこのブランチは保護されているのでGitHubへのpushはできていません。

ブランチ保護によって誤ってmainブランチを直接変更してしまうことは防げますが、作業ブランチに切り替えることを忘れて作業ブランチのつもりで編集して「Save document」をクリックして「ファイルを保存しました」とメッセージが出て、保存したと思ったら実際はどのブランチにも保存されていないという事故がこれでは防げません。

![Screen Shot 2022-01-28 at 11 10 02](https://user-images.githubusercontent.com/3324737/151475053-ffe84ac0-c7f6-4fbc-b0d3-7ac2053fea3e.png)

まずは、「Save document」でGitHubへの書き込みができなかったことをエラーメッセージとして出すとよいかと思います。

将来的には、次のような改良が考えられます：

- 書き込みができないブランチでは直接編集できないようにする
- 書き込みができないブランチでは編集して保存しようとしたとき、ブランチの作成ができるようにする。
  - 参考：GitHubのWebから書き込みができないブランチのファイルを編集したときの新しいブランチの作成（下図）
    <img width="787" alt="Screen Shot 2022-01-28 at 11 19 06" src="https://user-images.githubusercontent.com/3324737/151475814-dce83414-c1b1-42f4-9919-0979e9e38fc3.png">

**Comment by AyumuTakai** [comment]
原因にかかわらず保存できなければエラーを表示するよう修正しました。

ブランチの作成については次の開発者にお願いします。

**Comment by MurakamiShinyu** [comment]
保護ブランチでSave documentしたとき、「ファイルの保存に失敗しました。」が表示されるようになったこと確認しました。
このissueはクローズします。

**Comment by KazuyoshiTokue** [comment]
迅速に対応いただき、ありがとうございます。
