### ISSUE TITLE
保存に失敗しました status code 400（または500）

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#147]
Pubでのファイルの保存や作成でエラー発生するようになり、PubからGitHubへのコミットが出来なくなっている状態です。

https://vivliostyle-pub-develop.vercel.app/
および
https://vivliostyle-pub-develop-proto.vercel.app/
の両方で、
いくつかのGitHubリポジトリでのPubでの編集やファイル作成を試してみましたが、いずれもエラーになります（develop版とdevelop-proto版とでエラーが違うことについては後述 ）。
ユーザーから「PUBで文書が保存できない」と報告を受けて、私の方でもテストして確認したので、特定ユーザーアカウントだけでの問題でもないようです。

以下、こちらでテストした結果です：

まず、
https://vivliostyle-pub-develop.vercel.app/
でGitHubリポジトリ https://github.com/MurakamiShinyu/pubtest2 のファイル README.md を編集して Save Document をクリックすると、

![スクリーンショット 2022-02-28 15 16 07](https://user-images.githubusercontent.com/3324737/155936836-0201ae90-f118-48d4-9d6b-02d6a9a628c8.png)

このように、「保存に失敗しました status code 400」が発生します。

https://vivliostyle-pub-develop-proto.vercel.app/
のほうで、同様のテストをしようとしたところ、まずエディターでの編集で文字を入力しはじめたところで、
「ファイルが保存されていません。変更を破棄しますか？」
というalertが出ました。文字を入力しはじめたところでこれが出るのは異常です。

![スクリーンショット 2022-02-28 15 22 08](https://user-images.githubusercontent.com/3324737/155937834-be75f03b-7b41-4881-84b9-47ab40d05be5.png)

ここで「キャンセル」をクリックして、文字入力を続けて、それから Save Document をクリックすると、

![スクリーンショット 2022-02-28 15 23 32](https://user-images.githubusercontent.com/3324737/155938339-cd17a494-1c72-41fb-b757-da15c7df65cc.png)

このように、「保存に失敗しました status code 500」が発生します。

また、ファイル作成を試みたところ、次のようにエラーになりました。

![スクリーンショット 2022-02-28 16 06 51](https://user-images.githubusercontent.com/3324737/155939243-1357a638-dece-423b-bb17-bb073faffa40.png)

>ファイル(…)が作成できませんでした:Request failed due to following response errors: - Nullability mismatch on variable $additions and argument additions ([FileAddition] / [FileAddition!]) - Nullability mismatch on variable $deletions and argument deletions ([FileDeletion] / [FileDeletion!]) - Type mismatch on variable $headOid and argument expectedHeadOid (String! / GitObjectID!)

このエラー内容は、develop版でもdevelop-proto版でも同じです。また、このときDevToolsのコンソールには特に何も出力されません。

**Comment by AyumuTakai** [comment]
ここのところ一切の変更をしていないのですが、もしかしたらGitHub APIの実行回数制限に掛っているのかもしれません。

https://docs.github.com/ja/developers/apps/building-github-apps/rate-limits-for-github-apps

**Comment by MurakamiShinyu** [comment]
#148 にて修正されて、その後、問題なく保存できていることが確認できたのでクローズします。
