### ISSUE TITLE
出力するPDFにテーマを適用する

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#151]
march2022開発者会議で、@takanakahikoさんは[以下のようにコメント](https://github.com/vivliostyle/community/issues/97#issuecomment-1059654505)されていました。

> ただ出力される PDF にテーマが適用されていないのは問題かなと思っています。今はそれに取り組んでいます。これは遅くとも１週間程度で終わらせたいのですが、少なくともこれが終わるまでアルファ版リリースは待っていただきたいです。

**Comment by AyumuTakai** [comment]
現在のPDFエクスポートは選択されたファイルではなく、vivliostyle.config.jsを元にビルドを行ないます。

* 現在選択しているファイルのみをPDF化
* vivliostyle.config.js に従ってPDF化

の両方のニーズがあると思いますが、要件として整理されていないと思います。なのでメニューがひとつしかありません。

vivliostyle.config.jsに従って全体をビルドするものの、Pubで選択したテーマを使用するパターンもありえます。

**Comment by MurakamiShinyu** [comment]
> 出力されたPDFに複数の問題がある

複数の問題は、別々のissueに分けてください。

**Comment by ogwata** [comment]
> の両方のニーズがあると思いますが、要件として整理されていないと思います。なのでメニューがひとつしかありません。

なるほど、了解しました。
そこで相談です。
現在のアルファ版では「vivliostyle.config.js に従ってPDF化」（つまり現状）でOKとし、次のベータ版で「現在選択しているファイルのみをPDF化」を実現するということではどうでしょう？

**Comment by ogwata** [comment]
問題ごとにIssueを切り分け、日程については  #89 で話し合うことにしましょう。
