### ISSUE TITLE
Vivliostyle CLI のバージョンが古い

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#168]
Vivliostyle Pubで出力されたPDFの文書のプロパティを見ると

> アプリケーション：　Vivliostyle (Vivliostyle.js 2.12.1; Chromium)
> PDF 変換：　Skia/PDF m97

となっています。（詳細は次の画面キャプチャ）

![スクリーンショット 2022-04-20 11 54 22](https://user-images.githubusercontent.com/3324737/164141021-193f9c6e-3671-44a7-b1eb-10d970d56929.png)

この「Vivliostyle.js 2.12.1」「Skia/PDF m97」の情報から、使われている Vivliostyle CLI バージョンは [4.5.0 (2021-11-30)](https://github.com/vivliostyle/vivliostyle-cli/blob/main/CHANGELOG.md#450-2021-11-30) であることが分かります（CLIのCHANGELOGで 4.5.0のひとつ前の 4.4.1 で「Update Vivliostyle.js to 2.12.1」、それから4.5.0 で「Update Puppetter-core to 12.0.1」があり、Puppeteerのこのバージョンで使われるChromiumバージョン97で「Skia/PDF m97」の情報と一致）。

Vivliostyle CLIのバージョンが5ヶ月くらい古いものです。なぜでしょう？　次のDockerfileを見ると、

https://github.com/vivliostyle/vivliostyle-pub/blob/e6b3f27b042502ffa4fb5ee59be059f63b08d1e7/cloud-run/Dockerfile#L1

ちゃんと vivliostyle/cli の最新版（`ghcr.io/vivliostyle/cli:latest`）が指定されているようです。

Vivliostyle CLI の Docker image のバージョン履歴
https://github.com/vivliostyle/vivliostyle-cli/pkgs/container/cli/versions
を見ても latest タグは正しく現在最新リリースバージョンの 4.9.0 になってます。

**Comment by takanakahiko** [comment]
ありがとうございます。調査してみますね。
