### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/vivliostyle-pub#17]

**Comment by AyumuTakai** [comment]
アルファ版 #142 で i18n-next パッケージを使って多国語対応しました。

web/src/locales/en/translation.json
web/src/locales/ja/translation.json

が対応表になっています。 

形式は以下の通りです。

```
"キー文字列":"表示文字列 {{埋め込み変数}}"
```

文言のチェックをお願い致します。

**Comment by AyumuTakai** [comment]
対応言語を増やす場合には、 web/src/pages/_app.tsxでjsonファイルをimportして、i18nのresourcesにプロパティを追加してください。

**Comment by MurakamiShinyu** [comment]
対応済みなのでクローズします。
