### ISSUE TITLE
PDFが生成されない

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#178]
Vivliostyle PubでのPDF生成が、昨日まではできたのに、いまやってみると「ビルドを開始しました」でぐるぐるしたままになります。（現象はクローズ済みの #91 と同じ）

**Comment by MurakamiShinyu** [comment]
> 昨日まではできたのに

それをテストしたのは3日前の4/19でした。そのときもPDF生成ができたり出来なかっただったのですが、entryのファイル数やファイルの大きさを小さくしてテストしたところ、PDF生成ができるようになってました。その同じ状態のリポジトリで今日テストしたところ、PDFが出来なくなっていました。

**Comment by takanakahiko** [comment]
これで直ったかなと思います
https://github.com/vivliostyle/vivliostyle-pub/commit/e4b6b8ff43c91557e8e1636d55dc44f777b7ff51

**Comment by ogwata** [comment]
お疲れさまです！　ただ、残念ながら解消していないように見えます。
こちらのリポジトリで試してみましたが、1分以上経過してもPDFが出力されません。
https://github.com/ogwata/slide-20220423-2

https://user-images.githubusercontent.com/31482860/164773126-d063f8a7-80bb-4bf4-9c1b-074edbe7b023.mov



動画を撮ってみました。
