### ISSUE TITLE
Vercel banner required to obtain the Vercel sponsorship for open source projects

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#182]
See the Sponsorship Criteria on https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project.

**Comment by takanakahiko** [comment]
すべてのページのフッターにVercel bannerを設置して申請する必要がある

**Comment by takanakahiko** [comment]
文字だけでもいいかも？要検討

**Comment by MurakamiShinyu** [comment]
参考：Vivliostyle.js でのVercel banner設置：

- https://github.com/vivliostyle/vivliostyle.js/pull/922

**Comment by MurakamiShinyu** [comment]
PR #188 にて、最小限の対応をしてみました。

README.md の最後に、
![Screen Shot 2022-06-03 at 12 44 18](https://user-images.githubusercontent.com/3324737/171781967-faac3128-008d-4641-b80c-2a2f355f6a65.png)

Vivliostyle PubのLoginの画面下部に、

![Screen Shot 2022-06-03 at 12 32 33](https://user-images.githubusercontent.com/3324737/171781678-30179ce2-8493-4970-b2eb-4f33b769a2b8.png)
