### ISSUE TITLE
http mode not working

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#193]
#163 (Enable http mode)で Action メニューに "Using HTTP Mode In Build" が追加されたが、それをONにしても実際は機能していない。

次のように確認できる。

Action メニューで、"Using HTTP Mode In Build" に✔️をつけてから、"Export→PDF" を実行。

![Screen Shot 2022-06-20 at 23 14 51](https://user-images.githubusercontent.com/3324737/174623596-1eef90f1-18e9-4c7b-9402-436de2800636.png)

そのとき、DevToolsで、MenuBar.tsx の

https://github.com/vivliostyle/vivliostyle-pub/blob/ee71525c8baa88c34f987c33536500f60820351f/web/src/components/MenuBar.tsx#L112

にブレークポイントを設定して、isUsingHttpModeInBuild の値を調べると、false になっている：

![Screen Shot 2022-06-20 at 23 23 42](https://user-images.githubusercontent.com/3324737/174624047-38848ae4-86c6-4cc8-a124-042917fc8e8f.png)

変数 isUsingHttpModeInBuild は次のところで定義されているが、この `onBuildPDFButtonClicked()` が呼ばれるとき、メニューでの "Using HTTP Mode In Build" の状態のとおりになっていないようだ。

https://github.com/vivliostyle/vivliostyle-pub/blob/ee71525c8baa88c34f987c33536500f60820351f/web/src/components/MenuBar.tsx#L109

## http mode は常に true とするべきでは？

メニューから "Using HTTP Mode In Build" を削除して、http mode は常に true とするとよいと思いますが、それで問題あるでしょうか？

**Comment by takanakahiko** [comment]
> メニューから "Using HTTP Mode In Build" を削除して、http mode は常に true とするとよいと思いますが、それで問題あるでしょうか？

問題ないような気がしますね。一度このまま変更を取り込んでみます。
