### ISSUE TITLE
'Cannot read properties `target` of of null`のエラーでログインできない

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#224]
以下は提携先企業からのレポートである

## 環境

- Windows 10 バージョン22H2
- Microsoft Edge 最新版
- Chrome 最新版

## 報告

Vivliostyle Pubの設定をしようとているのですが、
添付ファイルのようなエラーが出て、先へ進めません。

画面右上にユーザーネームが表示されないので、前の段階でうまくいってないと思います

以下のご案内に従って、Githubアカウントを作り、Vivliostyleを開き、
アプリのインストールと事前準備の完了まですませて、
「ファイル一覧ペインからの操作」のところのスクリーンショットです。
https://vivliostyle.github.io/docs-vivliostyle-pub/#/ja/file-and-folder-operations/file-list-pane-operations

1回目はMicrosoft Edgeでうまくいかず、2回目Chromeでメールを変えて同じことを繰り返したのですが、まったく同じ結果でした。

GitHubの登録と、リポジトリの作成まではうまっく言っているようですが、Vivliostyle Pubとの連携が取れていないような印象です。

## 小形の補足

折り返し、ログインの手順を確認したが、正しい手順で操作しているようだ。
なお、Pubにログイン直後の段階で、すでに画面右上のアカウント名が表示されていないとのこと

**Comment by MurakamiShinyu** [comment]
次と同じエラーで重複するのでこれは閉じます。

- https://github.com/vivliostyle/vivliostyle-pub/issues/217
