### ISSUE TITLE
書き出し先を dist にすることに関する検討

### ISSUE THREAD

**Issue by takanakahiko** [vivliostyle/vivliostyle-pub#55]
## 概要

See also : https://github.com/vivliostyle/community/wiki/Vivliostyle-Pub-v1-Req#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A8%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E6%A7%8B%E9%80%A0

現状はこういうディレクトリで WebBook をビルドすると

```
package.json
README.md
LICENSE
vivliostyle.config.js
text/
assets/
themes/
```

現状だとこうなる

```diff
+ index.html
+ publication.json
+ html/
package.json
README.md
LICENSE
vivliostyle.config.js
text/
assets/
themes/
```

そうではなく、こうしたらどうかという提案

```diff
+ dist/WebBook/index.html
+ dist/WebBook/publication.json
+ dist/WebBook/html/
+ dist/WebBook/assets/
+ dist/WebBook/themes/
package.json
README.md
LICENSE
vivliostyle.config.js
text/
assets/
themes/
```

EPUB ビルド時はこうする。
こうすると複数の書き出し形式が共存できて便利そう。

```diff
+ dist/EPUB/mimetype
+ dist/EPUB/META-INF/container.xml
+ dist/EPUB/package.opf
+ dist/EPUB/xhtml/
+ dist/EPUB/assets/
+ dist/EPUB/themes/
package.json
README.md
LICENSE
vivliostyle.config.js
text/
assets/
themes/
```

### 補足

- WebBook の公開時に /dist/WebBook  内を公開すればよいためシンプル
- WebBook のエクスポート時に /dist/WebBook  内を Zip にすればよいためシンプル
- markdown も公開したいニーズもあるかもという話があったが、それは利用者がコピーすれば良さそうな気がする
- dist を gitignore すれば良いのでシンプル

**Comment by MurakamiShinyu** [comment]
[ファイルとディレクトリ構造](https://github.com/vivliostyle/community/wiki/Vivliostyle-Pub-v1-Req#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A8%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E6%A7%8B%E9%80%A0) で、原稿(.md)と変換したHTMLファイルのディレクトリを同じ `content/` にしてみました。

編集作業時の自動ビルドでは同じ `content/` ディレクトリに原稿と変換したHTMLファイルの両方が存在することになります。そして、リリース用のビルドでは、変換したHTMLファイルだけがリリース用の content ディレクトリに出力されることになります。

メリット:
- contentディレクトリ内を階層化（記事や著者ごとに分けるなど）してその中に画像などを含めることができる。
  - cf. [「Vivliostyleで本を作ろう」の原稿の content ディレクトリ](https://github.com/spring-raining/tbf09-draft/tree/master/content) はそうなっている。
- 原稿とHTMLとでディレクトリ名が変わらないので、相対URLでのファイルの参照が簡単。拡張子だけ変えればよい（.md→.html）。

（Vivliostyle CLI v3 での distDir を指定しない場合のデフォルトの動作も、HTMLを別のところに出力するのではなく、原稿と同じ場所に拡張子だけ変えて出力するのでよいのでないでしょうか）

**Comment by MurakamiShinyu** [comment]
> （Vivliostyle CLI v3 での distDir を指定しない場合のデフォルトの動作も、HTMLを別のところに出力するのではなく、原稿と同じ場所に拡張子だけ変えて出力するのでよいのでないでしょうか）

この案をVivliostyle CLI v3.0 の仕様の見直し案の中に書きました。
https://github.com/vivliostyle/community/wiki/Vivliostyle-CLI-v3.0-new-spec

> **build options**
> …
> ```
>   --dist-dir <directory>        dist dir for webbook where publication.json and other files are generated.
>                                 default to undefined (use current dir as webbook root dir).
> ```

`--dist-dir` 指定なし(undefined)の場合は「HTMLを別のところに出力するのではなく、原稿と同じ場所に拡張子だけ変えて出力」、指定した場合は現在と同様の動作ということです。

また、入力がMarkdown原稿である場合のbuildのデフォルトの動作がwebbookの生成（md→html変換、pub-manifest生成）とPDF生成の両方を行うというのは現在とだいたい同じですが、別々にも行えるように次のオプションを追加：

> ```
>   -n, --no-generate-webbook     no generate webbook (use existing publication.json and html files)
>   -N, --no-output               no output (only generate webbook)
> ```

**Comment by takanakahiko** [comment]
Vivliostyle CLI での仕様に従うので、一旦この Issue は閉じておきます〜
