### ISSUE TITLE
Chrome以外で、Vivliostyle-Pubの起動に失敗する

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#56]
1. ターミナルでリポジトリのディレクトリに移動し、以下のコマンドを実行

```
$ cd web
$ yarn install
$ yarn dev
```

2. Chromeを起動し http://localhost:9990 にアクセスすると、下記のような画面になるので、ユーザ名の部分をクリック（ブラウザの起動以前から、ChromeでGitHubにログインしていた）
<img width="1472" alt="スクリーンショット 2020-12-03 17 34 37" src="https://user-images.githubusercontent.com/31482860/100994329-d2553500-3599-11eb-995b-e07c06b9e1a4.png">

3. Vivliostyle-Pubの起動に成功
<img width="1472" alt="スクリーンショット 2020-12-03 17 36 15" src="https://user-images.githubusercontent.com/31482860/100994494-f87ad500-3599-11eb-8927-35aea85ad9f9.png">

4. 次に、Safariを起動し、同じく http://localhost:9990 にアクセスすると、このような画面になり起動できない
<img width="1424" alt="スクリーンショット 2020-12-03 17 37 26" src="https://user-images.githubusercontent.com/31482860/100994537-092b4b00-359a-11eb-9752-050d5d427762.png">

5. SafariではGitHubにログインしていなかったことを思いだし、あらためてサインイン
<img width="1424" alt="スクリーンショット 2020-12-03 17 39 20" src="https://user-images.githubusercontent.com/31482860/100994672-2f50eb00-359a-11eb-895a-7d0ccf2a8879.png">

6. その上で http://localhost:9990 にアクセスする
<img width="1424" alt="スクリーンショット 2020-12-03 17 39 47" src="https://user-images.githubusercontent.com/31482860/100994805-514a6d80-359a-11eb-8e85-a7d1efbd2739.png">

7. ログイン画面になるので、「Login」をクリック
<img width="1424" alt="スクリーンショット 2020-12-03 17 40 22" src="https://user-images.githubusercontent.com/31482860/100994863-66270100-359a-11eb-9f9b-4e8fc01a424a.png">

8. この画面のまま遷移せず、起動に失敗する 
<img width="1424" alt="スクリーンショット 2020-12-03 18 20 28" src="https://user-images.githubusercontent.com/31482860/100995496-30cee300-359b-11eb-9612-3b895e1343e3.png">

9. つぎにFirefoxを起動し、GitHubにサインイン
<img width="1423" alt="スクリーンショット 2020-12-03 17 42 47" src="https://user-images.githubusercontent.com/31482860/100995684-7390bb00-359b-11eb-8a19-d8101ed1de60.png">

10. ぶじにGitHubにサインイン成功
<img width="1423" alt="スクリーンショット 2020-12-03 17 44 24" src="https://user-images.githubusercontent.com/31482860/100995742-873c2180-359b-11eb-8415-e9c097025935.png">

11. 新規タブを開いて http://localhost:9990 にアクセス
<img width="1423" alt="スクリーンショット 2020-12-03 17 44 51" src="https://user-images.githubusercontent.com/31482860/100995814-a33fc300-359b-11eb-8728-4bff90a3e897.png">

12. ログイン画面になるので「Login」をクリックする
<img width="1423" alt="スクリーンショット 2020-12-03 17 44 58" src="https://user-images.githubusercontent.com/31482860/100995856-b2267580-359b-11eb-8684-30800ca71763.png">

13. 以下の画面のまま変化せず、Firefoxでも起動に失敗する
<img width="1423" alt="スクリーンショット 2020-12-03 17 45 15" src="https://user-images.githubusercontent.com/31482860/100995891-beaace00-359b-11eb-9dec-ea628610b759.png">

**Comment by ogwata** [comment]
同一のアカウントで、3種類のブラウザに対してログインしてみました。

- Firefoxはレンダリングしない（00:00-00:40）
- Chromeは問題なし（00:40-01:04）
- Safariはログインできない（01:04-02:19）

ChromeとSafariは https://github.com/vivliostyle/vivliostyle-pub/issues/56#issuecomment-906464915 と同じなのに対し、Firefoxはログインできるけれど、レンダリングをしないという症状です。（じつは、この時は出ていませんが、録画する直前に試した際には[404エラーがでました](https://github.com/vivliostyle/vivliostyle-pub/issues/81)）。このFirefoxの症状は、クローズした https://github.com/vivliostyle/vivliostyle-pub/issues/77#issuecomment-900293467 で報告したものと同一です。

なお、Safariでは2回ログインしようとしていますが、ログイン画面に戻ってしまうのは、いずれもログインボタン押下後30秒ですね。

https://user-images.githubusercontent.com/31482860/131839541-f6b6e398-0d66-4eb0-b644-e3a214967fb4.mov

**Comment by ogwata** [comment]
21時に投稿したコメントは、以前のURL https://vivliostyle-pub-develop-proto.vercel.app/ へのアクセス結果でした。失礼しました。お詫びして削除します。

あらためて3種のブラウザで https://vivliostyle-pub-develop.vercel.app/ にアクセスした動画を投稿します。ただ、状況は悪くなっているように見えます。

- Firefoxはプレビューが404エラー（00:00-01:03）
- Chromeもプレビューが404エラー（01:03-02:00）
- Safariはログインできない（02:00-03:11）

404エラーは3つあるファイルのどれでも発生し、リロードしても、スタイルを変更しても治りません。

Safariでは2回ログインしようとしていますが、ログイン画面に戻ってしまうのは、いずれもログインボタン押下後30秒のようです。

https://user-images.githubusercontent.com/31482860/131865728-2c2c2b3c-cca3-4610-a175-32383f263723.mov

なお、ChromeでGitHubのセッティングからGitHub Appsや認証情報の削除をした動画が以下になります。ただ、やはり404エラーは治りませんでした。

https://user-images.githubusercontent.com/31482860/131865924-9345c190-c2fb-4b56-a66c-8a73f5e6f4dc.mov

**Comment by MurakamiShinyu** [comment]
私も試してみました。

- Mac
  - Chrome 93.0.4577.63 (Official Build) (arm64) - OK
  - Chrome Canary 95.0.4635.0 (Official Build) canary (arm64) - プレビューが404エラー
  - Firefox 91.0.2 - プレビューが404エラー
  - Firefox Nightly 94.0a1 (2021-09-06) 
    - ログインできない
      - Login しようとしても Login に戻る
  - Safari 14.1.2 (16611.3.10.1.6) 
    - GitHubリポジトリ一覧が出るがクリックしても開かない
      - GitHubリポジトリ一覧が表示されるとき、JavaScriptコンソールで "SyntaxError: Invalid regular expression: invalid group specifier name" が出ている
- Windows
  - Chrome 93.0.4577.63（Official Build） - プレビューが404エラー
  - Firefox 91.0.2 - プレビューが404エラー
  - Microsoft Edge 93.0.961.38 (公式ビルド) - プレビューが404エラー

以上テストした範囲では、正常に動くのはMac上の現行バージョンのChromeだけでした。同じChrome 93でもWindowsではプレビューが404エラーになりました。MacのChromeでもCanary版(Chrome 95)では同じくプレビューが404エラーになりました。

**Comment by AyumuTakai** [comment]
現在、プレビューが404エラーになる件を調査中です。

簡単なプログラムを作成して検証したところ、
Mac(intel)版Chrome 94では、XMLHttpRequestとFetch APIでCache Storageにアクセスしないようです。
Image要素やiframe要素のsrcなどにURLを指定するとキャッシュから読み出せています。

vivliostyle/viewerのnet.tsのajax関数でXMLHttpRequestを使ってソースになるHTMLファイルを読んでいるようですので、
キャッシュに追加したファイルを読み込めていない可能性があります。

ajax関数を改造して先にキャッシュを探す処理を入れるようにしてみてはどうでしょうか。

**Comment by AyumuTakai** [comment]
ブラウザ側でのXMLHttpRequestの実装がfetchイベントを発火させるように変わらない限り、とり急ぎ問題を解決するにはvivliostyle.jsに手を入れるしかないのでは。

方法としては以下の3つがあると思います。

* 現状のsetup-viewer.jsでパッチを当てる(minifyされたvivliostyle-viewer.jsにパッチを当てるのは大変そう)
* vivliostyle.jsにPub用のブランチを作成しweb/package.jsonに指定する
* patch-packageなどでVivliostyle-Pubにyarn install後にパッチを当てる

**Comment by MurakamiShinyu** [comment]
この修正で、 Vivliostyle Pub 以外での Vivliostyle.js の利用で問題が起きることがないのであれば、この修正を入れた Vivliostyle.js をリリースしようと思います。

**Comment by MurakamiShinyu** [comment]
@AyumuTakai 

vivliostyle.js のほうに pull req しませんか。

**Comment by AyumuTakai** [comment]
404エラーの原因を探るための簡易版で、HTMLなどのテキストファイルのみキャッシュされるという前提の修正です。
画像などのバイナリデータをキャッシュした場合には正常動作しないと思いますので、そのあたりはpubでどうするのか、
相談したいと思います。

**Comment by AyumuTakai** [comment]
画像をリポジトリに追加してVFMで表示させる記述をしたところviewer内で404エラーになってしまうため、原因を調べています。
htmlのときのようにViewerが404エラーを表示するのではないので異なる原因によるものだと思います。

このエラーを修正できたらプルリクを投げます。

**Comment by MurakamiShinyu** [comment]
Safari (WebKit) で動かない問題は次のissue:

- https://github.com/vivliostyle/vivliostyle-pub/issues/184

**Comment by MurakamiShinyu** [comment]
https://github.com/vivliostyle/vivliostyle-pub/issues/184#issuecomment-2179875455

> Safari (WebKit) で "SyntaxError: Invalid regular expression: invalid group specifier name" となる問題は、2023年3月リリースのSafari 16.4で解決しているのでこのissueは閉じます。
> 
> Safariでログインできないのは別の理由です。(See https://github.com/vivliostyle/vivliostyle-pub/issues/297)


Safari (WebKit)での #138 の問題が解決したあと、Safari および Firefox でログインに失敗するのは以下の問題のためでした：

- #297 

> Starting **June 24, 2024**, implementing one of the options listed in the linked best practices below will be required for redirect sign-in to work on Google Chrome M115+. This is already required on Firefox 109+ and Safari 16.1+.

この "This is already required on Firefox 109+ and Safari 16.1+" のとおり、FirefoxとSafariでは動きません。そして、Chromeでも対応しないでいると6月24日からは動かなくなるということです。

そこで次のPRでこの対応をしました：

- #308

これによって、Chrome以外でもログインできるようになるはずです。
