### ISSUE TITLE
最初のプレビュー表示で "Failed to fetch a source document from https://vivliostyle-pub-develop.vercel.app/vpubfs/index.html (404 Not Found)"

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle-pub#81]
https://vivliostyle-pub-develop-proto.vercel.app/
でテストすると、最初に編集とプレビュー画面が出ますが、Viewerに "Failed to fetch a source document from https://vivliostyle-pub-develop.vercel.app/vpubfs/index.html (404 Not Found)" のエラーが表示されます。
リロードする（または何か編集をする）とエラーが消えて正常な表示になります。
Markdownから変換したHTMLが生成される前にViewerを開いてしまうためではないかと思います。

![Screen Shot 2021-08-16 at 10 10 36](https://user-images.githubusercontent.com/3324737/129523361-83b41256-7994-4e9c-ae41-2011d145c8a7.png)

**Comment by MurakamiShinyu** [comment]
問題が修正されていること確認しました。

**Comment by AyumuTakai** [comment]
エラーが消えないままのときはコンテンツの準備に失敗していることがあるので原因を追求します。

**Comment by AyumuTakai** [comment]
img要素やCSSで参照している画像が1MBを超える場合にGitHubからの取得に失敗します。

大きなファイルを取得する方法も用意されていますが、取り急ぎエラー表示を行なうようプルリクエストに追加しました。

GitHubへのアクセスに使っているOctokitのバージョンも相当に古いので、アップグレードしてファイルサイズ制限の緩い方法に変更していく予定です。
