### ISSUE TITLE
PDFが出力できない

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#91]
「Action」メニューから「PDF」を選択すると、画面下部に「Build Started」という緑色のメッセージが表示され、「Action」メニュー左側にアニメーションで回転が表示されます。しかし、その後10分たってもPDFが生成されません。

動画を撮ってみました（容量制限のため8分でカットしてありますが、元ファイルは10分あります）。

https://user-images.githubusercontent.com/31482860/131157912-bb24fa2d-4454-4b8d-a548-870bbe187477.mov

**Comment by ogwata** [comment]
@takanakahiko 
[fix #91 ](https://github.com/vivliostyle/vivliostyle-pub/commit/a0296146019d14de1c456b74fd014cdc49346e76)のコミットありがとうございます！
ただ、私の環境では症状は全く変わらず、やはりPDFは出力されないままです。再度ご確認いただけないでしょうか。

**Comment by takanakahiko** [comment]
ですね、こっちでも直っていませんでした。引き続き調査してみます。

**Comment by ogwata** [comment]
ただ、[#90](https://github.com/vivliostyle/vivliostyle-pub/issues/90)の404エラーは出なくなったようです！

**Comment by ogwata** [comment]
確認してみましたが、私の環境では出力できませんでした。
動画を撮影してみましたので、ご確認ください。

https://user-images.githubusercontent.com/31482860/140229402-23ac669e-5eb0-4b75-938b-736b756e3483.mov

**Comment by takanakahiko** [comment]
なるほど、週末に確認してみますね。

**Comment by ogwata** [comment]
ログインからPDF出力までをDevToolで見てみました。
ご参考まで

https://user-images.githubusercontent.com/31482860/140513235-f4b8a36e-9972-4828-abef-3f0af2ca3541.mov

。

**Comment by takanakahiko** [comment]
数千ページになるようなプロジェクトでない限りは成功するようになりました！
ご報告＆デバック協力ありがとうございました！

**Comment by takanakahiko** [comment]
意図したレイアウトにならない問題はありそうですがその場合は別途Issueを建てましょう。
このIssueは一旦閉じますね。

**Comment by MurakamiShinyu** [comment]
私の方で今また試しましたが、PDF出力できません。reopenします。
「Your build has been started」のメッセージが出たあと、いつまで待っても処理中のぐるぐるが回ったままになります。

![Screen Shot 2022-01-28 at 13 38 33](https://user-images.githubusercontent.com/3324737/151488528-c2b70157-ce72-458d-b126-4956015bcdc3.png)

**Comment by AyumuTakai** [comment]
Slackのこちらのスレッドでも話を進めていますが、作業待ちです。

https://vivliostyle.slack.com/archives/CR14JBXCJ/p1640536666190400

**Comment by ogwata** [comment]
> Slackのこちらのスレッドでも話を進めていますが、作業待ちです。
> 
> https://vivliostyle.slack.com/archives/CR14JBXCJ/p1640536666190400

了解いたしました。
このIssueが解決できればアルファ版がリリースできます。
@takanakahiko さん、見通しをご報告いただけませんか。

**Comment by takanakahiko** [comment]
お待たせして申し訳ございません。
こちらですが、一部環境では上手く動いているような感じでして調査に難航しております。
また明日の朝と夜にも調べてみるのでもう少しお待ちください🙇‍♂️

**Comment by takanakahiko** [comment]
遅くなりましたが修正しました〜。
権限管理( IAM )に不適切なポイントがありうまく動いていなかったようです。

@ogwata さんにチェックしていただき問題なければ閉じていただければと。

**Comment by ogwata** [comment]
コミットありがとうございます！
ただ、1/28 @murakamiShinyu さんのコメントと同じ状況のようで、
Buildがスタートした後、いつまでも処理中のままです。
動画を撮ってみました。ご確認ください。

https://user-images.githubusercontent.com/31482860/156856822-0f3d00d9-a831-48a3-a60b-f2c5d51468fb.mov

**Comment by AyumuTakai** [comment]
https://vivliostyle-pub-develop.vercel.app/ で試したところ、私はPDF生成に成功しました。

何か条件が違うのでしょうか。

**Comment by ogwata** [comment]
@AyumuTakai 
コメントと検証、ありがとうございます。
こちらも同じURLです（ちなみに、まだグルグル回ってます）。
https://vivliostyle-pub-develop.vercel.app/

スクリーンショットで、なにか他の違いが分かるでしょうか？

**Comment by AyumuTakai** [comment]
動画見るとあまり条件変わらないですね。

私が以前試したときにPubのプレビューは表示されるけれど、vivliostyle.conf.jsのエラーでローカルのCLIでビルドは通らないケースがありました。
現在のPubのプレビューはvivliostyle.conf.jsの設定をthemeプロパティ以外使わないので、CLIと動作が違います。
もしかしたらDocker上のVivliostyleでエラーになっているのかも。

**Comment by ogwata** [comment]
Chromeの更新がきていたので再起動してやり直しましたが、やはり同様の症状です。
devtoolのスクリーンショットは以下の通りです。
<img width="1604" alt="スクリーンショット 2022-03-05 10 08 04" src="https://user-images.githubusercontent.com/31482860/156861243-d439a69c-0fba-45d7-b88b-7327af363897.png">

**Comment by AyumuTakai** [comment]
動画ではcross-siteのエラーは出ていないようですが、その後のスクリーンショットでは発生しているようです。
このエラーがどのタイミングで出るか、devtoolsを表示してからPDFエクスポートを試していただけませんか?
ビルド開始と同時に出るのか、暫くしてから出るのか確認したいです。

私の環境では、成功するリポジトリ、グルグルのままのリポジトリ双方でこのエラーは出ていません。

**Comment by ogwata** [comment]
ご指示のように最初からDevToolを立ち上げて動画を撮影してみましたが、今度は同じcross-siteのエラーがでません。
なお、この動画撮影の終了後（今も処理中）も、同じエラーが出ないままです。

https://user-images.githubusercontent.com/31482860/156863539-ed522cf5-2a33-47da-bf13-76ee1722e109.mov

**Comment by ogwata** [comment]
ちなみに、現在のdevtoolのスクリーンショットです。（動画の終了後、少しエラーが増えた）
<img width="1604" alt="スクリーンショット 2022-03-05 11 13 11" src="https://user-images.githubusercontent.com/31482860/156863755-64a73771-e327-43c0-b664-cc897a1835c5.png">

**Comment by AyumuTakai** [comment]
検証ありがとうございます。
cross-site関連は何か別の理由によるものではないかと思っていましたが、間違い無さそうです。

その他のエラーはReactの更新エラーのたぐいだと思いますが、エラー内容は表示されないでしょうか。

他に考えられる原因として、私のPubのアカウントはここ一ヶ月の間に一度削除して作りなおしています。
アカウントの削除機能は今のところ無いので、他の処理に割り込ませる形でfirebaseのAPIを操作して無理矢理実行しました。

PDFエクスポートに成功している @takanakahiko さんがPDFエクスポート機能を実装しているときに御自身のアカウントを作り直したりしていたらIAMの設定変更が反映されているか否かかもしれません。

**Comment by MurakamiShinyu** [comment]
私もテストしてみました。「ビルドを開始しました」でグルグル回ったままです。動画：

https://user-images.githubusercontent.com/3324737/156863964-85bf404c-c763-437e-a664-c8d67c738354.mov

**Comment by takanakahiko** [comment]
MurakamiShinyu/pubtest2 のビルドログを見てたんですが、 `Error: No input is set. Please set an appropriate entry or a Vivliostyle config file.` と出ていたので、 config 辺りに問題がありそうですかね？引き続き調査します。

**Comment by takanakahiko** [comment]
> 御自身のアカウントを作り直したりしていたらIAMの設定変更が反映されているか否かかもしれません。

これは違いますね。
CloudRun に付与する権限を変えた感じですので、個人のアカウントの作り直しが IAM に影響することはないはずです。

**Comment by AyumuTakai** [comment]
MurakamiShinyu/pubtest2 には vivliostyle.config.js が存在しないのでそれが原因だと思います。
vivliostyle.config.jsが無い場合や内容が処理できない場合にはビルドを実行しないなどの対応が必要ですね。
CLIのバージョンと整合性を取るのが大変そうですが。

CloudRunの権限について承知しました。他の原因を探ってみます。

**Comment by MurakamiShinyu** [comment]
> MurakamiShinyu/pubtest2 には vivliostyle.config.js が存在しないのでそれが原因だと思います。

そうでした。vivliostyle.config.js が存在するリポジトリでテストしたところ、PDF生成に成功しました。

https://user-images.githubusercontent.com/3324737/156865881-5c2d4731-fd40-4131-83a6-7643aa8719c9.mov

**Comment by AyumuTakai** [comment]
この制限はドキュメント等に書いていても嵌るユーザが出そうなのでvivliostyle.config.jsの存在チェックとCLIのinit相当の機能を実装してみます。

**Comment by ogwata** [comment]
> この制限はドキュメント等に書いていても嵌るユーザが出そうなのでvivliostyle.config.jsの存在チェックとCLIのinit相当の機能を実装してみます。

ありがとうございます。
ただ、私のmybookリポジトリにはvivliostyle.config.js はあるので、上記実装だけでは問題を解決できませんね……。

**Comment by AyumuTakai** [comment]
mybookリポジトリをクローンしてローカルのCLIで実行したところ、section-1.mdが無いというエラーになりました。

```
✖ Error: ENOENT: no such file or directory, open '/Users/takaiayumu/working/ogwata/mybook/section-1.md'
```

やっぱりvivliostyle.config.jsのチェック機能は必要ですね...。
もしくはDockerのstdoutとstderrをfirestoreに書き出してもらって、クライアント側でエラーハンドリングするか。

**Comment by ogwata** [comment]
> mybookリポジトリをクローンしてローカルのCLIで実行したところ、section-1.mdが無いというエラーになりました。
> 
なるほど、vivliostyle.config.js を修正して、出力してみます！

**Comment by ogwata** [comment]
vivliostyle.config.js からsection-1.mdの指定を削除して出力してみたところ、無事にPDFが出力できました！
私の認識が間違っていなければ、これでアルファ版のレベルに達したことになります。
開発者の皆さんに、心から感謝申し上げます
![スクリーンショット 2022-03-05 13 41 10](https://user-images.githubusercontent.com/31482860/156868223-d798ce4c-8d44-4748-b279-cc556ee30856.png)
。

**Comment by ogwata** [comment]
本日の開発者会議で了解が取れたので、本Issueはクローズします。

**Comment by ogwata** [comment]
本Issueについて、march2022開発者会議への、[@takanakahikoさんは](https://github.com/vivliostyle/community/issues/97#issuecomment-1059654505)で、以下のようにコメントされていました。

> ただ出力される PDF にテーマが適用されていないのは問題かなと思っています。今はそれに取り組んでいます。これは遅くとも１週間程度で終わらせたいのですが、少なくともこれが終わるまでアルファ版リリースは待っていただきたいです。

また、再テストしたところ、出力されるPDFには以下のような問題があるようです。

1. 選択されているファイルだけでなく、リポジトリにあるすべてのMDファイルがPDFに出力されてしまう
2. MDファイルにscript要素でWebフォントを埋め込んだ場合、PDFの内容が乱れる

上記のテストは、以下の2つのリポジトリでおこないました。

- [mybook](https://github.com/ogwata-book/mybook)
- [mybook-2](https://github.com/ogwata-book/mybook-2)

なお、上記2の症状は、mybook-2のMDファイルで確認し、出力されたPDFは下記にあります。

- [ogwata-book-mybook-2-9c1b2839-da73-402c-b648-d1dba0a4ab7e.pdf](https://github.com/vivliostyle/vivliostyle-pub/files/8201992/ogwata-book-mybook-2-9c1b2839-da73-402c-b648-d1dba0a4ab7e.pdf)

以上の理由で、本Issueを再オープンします。

**Comment by MurakamiShinyu** [comment]
@ogwata 
> 以上の理由で、本Issueを再オープンします。

このissueを再オープンではなく、別issueにするべきでしょう。
