### ISSUE TITLE
エディタとプレビューで別のファイルがロードされる

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vivliostyle-pub#94]
動画を撮ってみました。

https://user-images.githubusercontent.com/31482860/132017167-3a5056b6-6ca2-4fd5-b19d-60f2f6128d0a.mov

ブラウザはChrome（93.0.4577.63（Official Build））です。前半の緑色のテーマと後半の黒色のテーマの違いは、ログインしているGoogleアカウントの違いです。とはいえ、どちらもGitHubアカウントは同一なので、本来Vivliostyle Pubは同じ振る舞いをするはずです。

緑色のテーマ（00:00-01:59）では、左端のペインでファイルを選択するうち、エディタとプレビューで表示内容が食い違ってきます。

黒のテーマ（01:59-03:09）では404エラーでプレビューが表示されません。このエラーについては https://github.com/vivliostyle/vivliostyle-pub/issues/56#issuecomment-911774095 で報告ずみです。

**Comment by ogwata** [comment]
404エラーが出ているウィンドウのエラーログをふくめたスクリーンショットを追記します。

![スクリーンショット 2021-09-04 17 54 51](https://user-images.githubusercontent.com/31482860/132088918-551b7413-e31f-4e8c-be1a-03d3d0a382d2.png)

**Comment by ogwata** [comment]
エディタとプレビューで別のファイルがロードされるウィンドウのエラーログを追記します。
vivliostyle-viewer.jsとIndex.htmlのwarningです。

![スクリーンショット 2021-09-04 18 03 38](https://user-images.githubusercontent.com/31482860/132089123-dbd78af0-b364-4865-814a-8482e4248fc0.png)


![スクリーンショット 2021-09-04 18 04 02](https://user-images.githubusercontent.com/31482860/132089146-30c985ba-69eb-476f-b77c-adbda8abe343.png)

**Comment by MurakamiShinyu** [comment]
たぶん現在は解決済みなのでクローズします。まだこの現象があったら再オープンしてください。
